### ISSUE TITLE
Unlimited Ore Glitch

### ISSUE THREAD

**Issue by HarrisonCyr** [baxter-oop/AndOre#219]
Myself, Sam, and Owen had a glitch where we couldn't gain or lose any ore. We couldn't loot corpses for ore and when we placed buildings we didn't lose any ore. So we could place unlimited buildings.

**Comment by JCharante** [comment]
That is interesting, I guess there was in issue in the update_value functions between the node and sleipnir. I haven't seen this occur in over 180,000 ticks since then, and since the communication layer has been rewritten I will go ahead and close this issue. By all means if this happens again, please feel free to reopen the issue.
